project:
  type: website

website:
  title: "WV Deaths in Custody"
  favicon: img/favicon.png
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      - text: "Key Findings"
        href: key_findings.html
      - text: "Data"
        href: download_data.html
      - text: "Analysis"
        href: analysis.html
      - text: "Contact"
        href: contact.html
      - text: "Github"
        href: https://github.com/mr4909/wv_deaths_in_custody

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: left

execute:
  freeze: auto

resources:
  - fonts