project:
  type: website
  resources:
    - data/wvcbp_deaths.csv
    - fonts

website:
  title: "WV Deaths in Custody"
  favicon: img/favicon.png
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      - text: "Key Findings"
        href: key_findings.html
      - text: "Data"
        href: download_data.html
      - text: "Analysis"
        href: analysis.html
      - text: "Contact"
        href: contact.html
      - text: "Github"
        href: https://github.com/mr4909/wv_deaths_in_custody

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: left
    includes:
      in-header: includes/aos-header.html
      after-body: includes/aos-footer.html

execute:
  freeze: auto